name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Release binary
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Build (Linux)
        run: |
          cargo install cross
          cross build --target ${{ matrix.target }} --release --all-features --verbose
        if: startsWith(matrix.os, 'ubuntu')
      - name: build (macOS)
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --target ${{ matrix.target }} --release --all-features --verbose
        if: startsWith(matrix.os, 'macos')
      - name: Rename artifacts
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/rpbcopyd{,-${{ github.ref_name }}-${{ matrix.target }}}
          mv target/${{ matrix.target }}/release/rpbcopy{,-${{ github.ref_name }}-${{ matrix.target }}}
          mv target/${{ matrix.target }}/release/rpbpaste{,-${{ github.ref_name }}-${{ matrix.target }}}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: rpbcopyd-${{ matrix.target }}
          files: |
            target/${{ matrix.target }}/release/rpbcopyd-${{ github.ref_name }}-${{ matrix.target }}
            target/${{ matrix.target }}/release/rpbcopy-${{ github.ref_name }}-${{ matrix.target }}
            target/${{ matrix.target }}/release/rpbpaste-${{ github.ref_name }}-${{ matrix.target }}
